### ISSUE TITLE
Newsflash 3.0.1 in stable is broken

### ISSUE THREAD

**Issue by popey** [soumyaDghosh/newsflash-snap#1]
I'm using Ubuntu 23.04, and just noticed you published 3.0.1 (revision 23) to the stable channel. It's broken, as far as I can see.

```
alan@ziggy:~$ snap run newsflash
/snap/newsflash/23/usr/bin/io.gitlab.news_flash.NewsFlash: symbol lookup error: /snap/newsflash/23/usr/bin/io.gitlab.news_flash.NewsFlash: undefined symbol: gtk_list_header_get_item

```

**Comment by soumyaDghosh** [comment]
The problem happened is, I have gnome-42-2204 candidate installed, which has the latest gnome libraries, and while testing I forgot this thing. I'll revert it for now then.

**Comment by soumyaDghosh** [comment]
Hi.. I hope it's been fixed now. As much I tested, it's.
