### ISSUE TITLE
Application icon not displayed

### ISSUE THREAD

**Issue by Bruno-FGM** [soumyaDghosh/newsflash-snap#2]
Ubuntu 23.10
Snap Newsflash 3.0.2

The application is not displayed!
![image](https://github.com/soumyaDghosh/newsflash-snap/assets/97888863/32681b70-5fe8-4af7-8ec4-7b5c1d763dec)

**Comment by soumyaDghosh** [comment]
Just log out and login.

**Comment by Bruno-FGM** [comment]
ok, sorry, simple... thx for the quick answer... 
Works like a charm!
![image](https://github.com/soumyaDghosh/newsflash-snap/assets/97888863/489ce444-5e8d-426a-8fc2-67d530558ca1)
