### ISSUE TITLE
Cannot View Article in 3.1.6 (Ubuntu 22.04)

### ISSUE THREAD

**Issue by tornupnegatives** [soumyaDghosh/newsflash-snap#5]
I am using NewsFlash as a client for my self-hosted FreshRSS server. Lately, I cannot view any articles in the app or use the "Try to Show Full Content" button. The right-hand side is always empty. I'm wondering if anyone else is experiencing this issue.

**Comment by soumyaDghosh** [comment]
> I am using NewsFlash as a client for my self-hosted FreshRSS server. Lately, I cannot view any articles in the app or use the "Try to Show Full Content" button. The right-hand side is always empty. I'm wondering if anyone else is experiencing this issue.

Are you able to get any logs?

**Comment by janive** [comment]
@tornupnegatives I have a similar issue. Do you use a nvidia-graphicscard?

**Comment by tornupnegatives** [comment]
I am using an NVIDIA graphics card, yes. How can I go about producing some logs?

**Comment by soumyaDghosh** [comment]
Finally guys! I guess have some good news for you. I have a build for version `3.2.0` ready in the edge. Please give it a try and let me know. To install it, please install this before and connect the plugs manually. I'll update it in the readme.

**Comment by tornupnegatives** [comment]
Thanks for working on this! I've tried to update to the edge version, but I am getting an error.

```
➜  ~ sudo snap refresh newsflash --edge
error: cannot perform the following tasks:
- Ensure prerequisites for "newsflash" are available (cannot install prerequisite "ffmpeg-2404": no snap revision available as specified)
```

**Comment by soumyaDghosh** [comment]
> Thanks for working on this! I've tried to update to the edge version, but I am getting an error.
> 
> ```
> ➜  ~ sudo snap refresh newsflash --edge
> error: cannot perform the following tasks:
> - Ensure prerequisites for "newsflash" are available (cannot install prerequisite "ffmpeg-2404": no snap revision available as specified)
> ```


Please follow the commands from the `README`. You'll first need to install the dependencies and then newflash
https://github.com/soumyaDghosh/newsflash-snap?tab=readme-ov-file#edge

**Comment by janive** [comment]
I followed your manual. When I try to start newsflash, I get this error:

> jan@mars:~$ newsflash 
11:10:10 - INFO  - NewsFlash 3.3.0 (io.gitlab.news_flash.NewsFlash) (news_flash_gtk::app:80)
11:10:11 - INFO  - Loading backend freshrss            (news_flash:120)
11:10:11 - INFO  - Attempting to open config file: "/home/jan/snap/newsflash/72/.config/news-flash/freshrss.json" (news_flash::feed_api_implementations::freshrss::config:38)
11:10:11 - INFO  - Successful load from config         (news_flash_gtk::app:89)
libpxbackend-1.0.so: cannot open shared object file: No such file or directory
Failed to load module: /home/jan/snap/newsflash/common/.cache/gio-modules/libgiolibproxy.so
** (news_flash:21669): WARNING **: 11:10:11.353: Could not open /sys/class/dmi/id/chassis_type: Datei »/sys/class/dmi/id/chassis_type« konnte nicht geöffnet werden: Permission denied
** (news_flash:21669): WARNING **: 11:10:11.353: Could not open /sys/firmware/acpi/pm_profile: Datei »/sys/firmware/acpi/pm_profile« konnte nicht geöffnet werden: Permission denied
** (news_flash:21669): ERROR **: 11:10:11.355: Unable to spawn a new child process: Abspalten des Kindprozesses »/usr/lib/x86_64-linux-gnu/webkitgtk-6.0/WebKitNetworkProcess« gescheitert (No such file or directory)
Trace/Breakpoint ausgelöst (Speicherabzug geschrieben)


This are my current snaps:

> jan@mars:~$ snap list
Name                       Version                     Revision  Tracking          Herausgeber       Hinweise
bare                       1.0                         5         latest/stable     canonical✓        base
bitwarden                  2024.6.2                    113       latest/stable     bitwarden✓        -
canonical-livepatch        10.8.3                      282       latest/stable     canonical✓        -
core18                     20240416                    2823      latest/stable     canonical✓        base
core22                     20240408                    1380      latest/stable     canonical✓        base
core24                     20240528                    423       latest/stable     canonical✓        base
ffmpeg-2204                7.0                         114       latest/candidate  soumyadghosh      -
ffmpeg-2404                7.0.1                       1         latest/candidate  snapcrafters-bot  -
firefox                    127.0-2.1                   4424      latest/stable/…   mozilla✓          -
firmware-updater           0+git.5007558               127       latest/stable/…   canonical✓        -
gnome-3-28-1804            3.28.0-19-g98f9e67.98f9e67  198       latest/stable     canonical✓        -
gnome-42-2204              0+git.510a601               176       latest/stable/…   canonical✓        -
gnome-46-2404              0+git.b6706a3               24        latest/stable     canonical✓        -
gtk-common-themes          0.1-81-g442e511             1535      latest/stable/…   canonical✓        -
libreoffice                24.2.4.2                    322       latest/stable     canonical✓        -
mesa-2404                  24.0.5                      44        latest/stable     canonical✓        -
newsflash                  3.3.0                       72        latest/edge       soumyadghosh      -
snap-store                 0+git.ec3fa65               1147      latest/stable/…   canonical✓        -
snapd                      2.63                        21759     latest/stable     canonical✓        snapd
snapd-desktop-integration  0.9                         157       latest/stable/…   canonical✓        -
webkitgtk-6-gnome-2204     0+git.3c2f6a6               31        latest/stable     soumyadghosh      -
webkitgtk-6-gnome-2404     2.45.3                      1         latest/candidate  snapcrafters-bot  -

And the connections for newsflash
> jan@mars:~$ snap connections newsflash
Schnittstelle                    Plug                              Slot                                           Notizen
content[ffmpeg-2404]             newsflash:ffmpeg-2404             ffmpeg-2404:ffmpeg-2404                        manual
content[gnome-46-2404]           newsflash:gnome-46-2404           gnome-46-2404:gnome-46-2404                    -
content[gpu-2404]                newsflash:gpu-2404                mesa-2404:gpu-2404                             -
content[gtk-3-themes]            newsflash:gtk-3-themes            gtk-common-themes:gtk-3-themes                 -
content[icon-themes]             newsflash:icon-themes             gtk-common-themes:icon-themes                  -
content[sound-themes]            newsflash:sound-themes            gtk-common-themes:sound-themes                 -
content[webkitgtk-6-gnome-2404]  newsflash:webkitgtk-6-gnome-2404  webkitgtk-6-gnome-2404:webkitgtk-6-gnome-2404  manual
dbus                             -                                 newsflash:newsflash                            -
desktop                          newsflash:desktop                 :desktop                                       -
desktop-legacy                   newsflash:desktop-legacy          :desktop-legacy                                -
gsettings                        newsflash:gsettings               :gsettings                                     -
network                          newsflash:network                 :network                                       -
network-status                   newsflash:network-status          :network-status                                -
opengl                           newsflash:opengl                  :opengl                                        -
system-observe                   newsflash:system-observe          -                                              -
unity7                           newsflash:unity7                  :unity7                                        -
wayland                          newsflash:wayland                 :wayland                                       -
x11                              newsflash:x11                     :x11                                           -

**Comment by soumyaDghosh** [comment]
#3

Please follow this as it's not ready yet

**Comment by janive** [comment]
newsflash starts now. The rendering-problem persists. I have a blank page for every article.

```bash
jan@mars:~$ newsflash 
13:44:06 - INFO  - NewsFlash 3.3.0 (io.gitlab.news_flash.NewsFlash) (news_flash_gtk::app:80)
13:44:06 - INFO  - Loading backend freshrss            (news_flash:120)
13:44:06 - INFO  - Attempting to open config file: "/home/jan/snap/newsflash/72/.config/news-flash/freshrss.json" (news_flash::feed_api_implementations::freshrss::config:38)
13:44:06 - INFO  - Successful load from config         (news_flash_gtk::app:89)
libpxbackend-1.0.so: cannot open shared object file: No such file or directory
Failed to load module: /home/jan/snap/newsflash/common/.cache/gio-modules/libgiolibproxy.so

** (news_flash:14700): WARNING **: 13:44:07.040: Could not open /sys/class/dmi/id/chassis_type: Datei »/sys/class/dmi/id/chassis_type« konnte nicht geöffnet werden: Permission denied

** (news_flash:14700): WARNING **: 13:44:07.040: Could not open /sys/firmware/acpi/pm_profile: Datei »/sys/firmware/acpi/pm_profile« konnte nicht geöffnet werden: Permission denied
libpxbackend-1.0.so: cannot open shared object file: No such file or directory
Failed to load module: /home/jan/snap/newsflash/common/.cache/gio-modules/libgiolibproxy.so
13:44:07 - INFO  - WebKit version: 2.45.3              (news_flash_gtk::article_view::imp:145)
13:44:07 - INFO  - Networkmonitor connectivity: Local (available false) (news_flash_gtk::util:45)
libpxbackend-1.0.so: cannot open shared object file: No such file or directory
Failed to load module: /home/jan/snap/newsflash/common/.cache/gio-modules/libgiolibproxy.so

** (process:14858): WARNING **: 13:44:07.487: Could not open /sys/class/dmi/id/chassis_type: Datei »/sys/class/dmi/id/chassis_type« konnte nicht geöffnet werden: Permission denied

** (process:14858): WARNING **: 13:44:07.487: Could not open /sys/firmware/acpi/pm_profile: Datei »/sys/firmware/acpi/pm_profile« konnte nicht geöffnet werden: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 787x1035: Permission denied
13:44:07 - INFO  - pinging 'http://example.com/' succeeded (news_flash_gtk::util:57)
libpxbackend-1.0.so: cannot open shared object file: No such file or directory
Failed to load module: /home/jan/snap/newsflash/common/.cache/gio-modules/libgiolibproxy.so
13:44:10 - INFO  - Networkmonitor connectivity: Full (available true) (news_flash_gtk::util:45)

** (process:14993): WARNING **: 13:44:10.347: Could not open /sys/class/dmi/id/chassis_type: Datei »/sys/class/dmi/id/chassis_type« konnte nicht geöffnet werden: Permission denied

** (process:14993): WARNING **: 13:44:10.347: Could not open /sys/firmware/acpi/pm_profile: Datei »/sys/firmware/acpi/pm_profile« konnte nicht geöffnet werden: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 787x1035: Permission denied
libpxbackend-1.0.so: cannot open shared object file: No such file or directory
Failed to load module: /home/jan/snap/newsflash/common/.cache/gio-modules/libgiolibproxy.so
```

**Comment by soumyaDghosh** [comment]
Hi @janive Can you kindly try the `stable` channel once again with the `webkitgtk-6-gnome-2204` from candidate. To test this all you've to do is this

```bash
sudo snap refresh newsflash --stable
sudo snap refresh webkitgtk-6-gnome-2204 --candidate
```

**Comment by janive** [comment]
I reverted to the stable-channel. But the rendering issue still occurs. Perhaps I installed something wrong?

![grafik](https://github.com/soumyaDghosh/newsflash-snap/assets/30384277/b8a7e2a6-ef44-4c43-a7db-5d3e8418abc6)

![grafik](https://github.com/soumyaDghosh/newsflash-snap/assets/30384277/3b1ef77e-f330-4a99-b852-662b05b721ff)

![grafik](https://github.com/soumyaDghosh/newsflash-snap/assets/30384277/3c0f7375-dd55-48a7-bae4-c41b6e04926e)

**Comment by soumyaDghosh** [comment]
Hey @janive are you still facing this?

**Comment by soumyaDghosh** [comment]
Hii @janive @tornupnegatives this should be fixed now. We worked hard to debug this and now everything should be stable. Please let me know if this still occurs to you. Please don't hesitate to reopen this issue.
