### ISSUE TITLE
Not able to add new RSS feed

### ISSUE THREAD

**Issue by jan53n** [soumyaDghosh/newsflash-snap#6]
Am not able to add new feed from top left add icon.

![Screenshot from 2024-07-20 12-27-30](https://github.com/user-attachments/assets/203f0306-57b5-4d8f-b0cb-be89a7a9e65f)

**Comment by soumyaDghosh** [comment]
Hey @jan53n thanks for filing the issue. Sadly, this is an issue with your internet, which might happen randomly. I filed an issues with this upstream, and that's what I get.

https://gitlab.com/news-flash/news_flash_gtk/-/issues/639

Please, let me know if changing internet fixes the issue.

**Comment by jan53n** [comment]
changing proxy_url worked fine, thanks!

**Comment by soumyaDghosh** [comment]
Glad that it helped. If you love my work, please do consider supporting me. Closing this issue :-)
