### ISSUE TITLE
AppArmor policy should be extended to allow NewsFlash to access /proc/zoneinfo ?

### ISSUE THREAD

**Issue by kha84** [soumyaDghosh/newsflash-snap#7]
Hello there!

Thank you for packaging the NewsFlash for snap users. I found one interesting thing in journalctl logs:

```
Oct 14 12:12:40 magicbook14 kernel: audit: type=1400 audit(1728897160.361:1045): apparmor="DENIED" 
operation="open" class="file" profile="snap.newsflash.newsflash" name="/proc/zoneinfo" pid=29269 
comm="PressureMonitor" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
```

I guess this can be included to AppArmor profile

**Comment by soumyaDghosh** [comment]
Hi, thank you so much for using newsflash snap, and I'm glad that you liked it. The `/proc/zoneinfo` file is sensitive, so, even though the snap consists a plug to read it, it's not autoconnected. But, if you want to get rid of that log, you can manually connect it, from the Ubuntu Settings, the `Read process and system information` option

![image](https://github.com/user-attachments/assets/9740b117-5cc7-4f72-88b0-d9926e4527e1)

or via the terminal

```
sudo snap connect newsflash:system-observe
```

On a side note, if you like the snaps that I have published and maintain, please support my work by donations if possible. Your donations help me sustain my workflow. 

Thank you, have a great day.
